### PR TITLE
Resolve pipeline replay failures

### LINKED ISSUE #222: Facing errors when trying to replay a declarative Jenkins pipeline
### Jenkins Version

2.277.4

### JTE Version

2.3

### Bug Description

When I try to replay a declarative pipeline from Jenkins , It is not able to read the keywords and pipeline configuration from pipeline_config.groovy file and shows the errors for them. For example, I have defined the slave keyword in pipeline_config.groovy and using it inside Jenkins template but it gives me the below error during replay - 
groovy.lang.MissingPropertyException: No such property: **slave** for class: org.boozallen.plugins.jte.init.primitives.TemplateBinding
Possible solutions: class

Jenkins file template :
`
pipeline {
  agent {label slave}
.............
`
-------------------------
pipeline_config.groovy
`
@merge keywords{
  slave = "docker-slave"
}
`
It is also not able to identify the global variables of pipeline_config.groovy file inside Jenkins template during replay. Moreover, When I run it again after replacing those keywords and variables with actual values, it starts giving error with library step. For example, I have created a library for checkout() method and calling that from the Jenkins template but it gives me this error - 
java.lang.NullPointerException
	at org.jenkinsci.plugins.workflow.steps.scm.SCMStep.checkout(SCMStep.java:125)

 Is it a limitation with templating engine plugin ? Do we have any workaround for this ? Looking for your help in this. Thanks in advance.

### Relevant log output

_No response_

### Steps to Reproduce

Replay any declarative pipeline from Jenkins which is using keywords and global variables from pipeline_config.groovy file.

### LINKED ISSUE #225: [Bug]: Replay builds can't access JTE methods and properties
### Jenkins Version

2.313

### JTE Version

2.3

### Bug Description

When we run builds by replaying another one, we always get errors that methods do not exists:

```
No such DSL method 'on_pull_request'
```

Screenshot 2021-09-29 at 21 43 13

or other properties that we have declared (ie: in the general `pipeline_config.groovy`):

```
groovy.lang.MissingPropertyException: No such property: all_but_protected for class: org.boozallen.plugins.jte.init.primitives.TemplateBinding
    at groovy.lang.Binding.getVariable(Binding.java:63)
```

But if we trigger the build through the normal "Build Now" button, it works just fine.

Screenshot 2021-09-29 at 21 43 21

### Relevant log output

```shell
Replayed #2
Running in Durability level: MAX_SURVIVABILITY
[Pipeline] Start of Pipeline
[Pipeline] End of Pipeline
java.lang.NoSuchMethodError: No such DSL method 'on_pull_request' found among steps [ansiColor, deleteDir, dir, dockerFingerprintFrom, dockerFingerprintRun, echo, emailext, emailextrecipients, envVarsForTool, error, fileExists, findFiles, getContext, git, input, isUnix, junit, library, libraryResource, load, lock, mail, milestone, node, nodesByLabel, parallel, powershell, prependToFile, properties, publishChecks, publishHTML, pwd, pwsh, readCSV, readFile, readJSON, readManifest, readMavenPom, readProperties, readTrusted, readYaml, resolveScm, retry, script, sh, sha1, sha256, slackSend, slackUploadFile, slackUserIdFromEmail, slackUserIdsFromCommitters, sleep, stage, stash, step, tee, timeout, timestamps, tm, tool, touch, unarchive, withSonarQubeEnv, x509ClientCert, zip] or globals [currentBuild, docker, env, params, pipeline, scm]
	at org.jenkinsci.plugins.workflow.cps.DSL.invokeMethod(DSL.java:216)
	at org.jenkinsci.plugins.workflow.cps.CpsScript.invokeMethod(CpsScript.java:122)
	at jdk.internal.reflect.GeneratedMethodAccessor64306.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:163)
	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onMethodCall(GroovyInterceptor.java:23)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:158)
	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onMethodCall(SandboxInterceptor.java:143)
	at org.kohsuke.groovy.sandbox.impl.Checker$1.call(Checker.java:161)
	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:165)
	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
	at WorkflowScript.run(WorkflowScript:1)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at jdk.internal.reflect.GeneratedMethodAccessor151.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ClosureBlock.eval(ClosureBlock.java:46)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:139)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
[Bitbucket] Notifying pull request build result
[Bitbucket] Build result notified
Finished: FAILURE
```

### Steps to Reproduce

Just try to replay a build.

### PR DESCRIPTION
**Pull request by steven-terrana**
# PR Details

fixes #222 
fixes #225 

## Description

The `TemplatePrimitiveCollector` action that's responsible for giving the pipeline access to `TemplatePrimitive`s was not being added for replays of pipelines.

## How Has This Been Tested

unit tests reproduced the error and then passed with the fix. 

## Types of Changes

- [x] Added Unit Testing
- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have added the appropriate label for this PR
- [x] If necessary, I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by steven-terrana** [comment]
tests passing locally but failing in GH actions 🤔

File: src/main/groovy/org/boozallen/plugins/jte/job/TemplateFlowDefinition.groovy [hunk 1]
```diff
@@ -54,11 +57,19 @@ abstract class TemplateFlowDefinition extends FlowDefinition {
...
     FlowExecution create(FlowExecutionOwner owner, TaskListener listener, List<? extends Action> actions) throws Exception {
-        // if this is a replay run, just skip initialization
-        for (Action a : actions) {
-            if (a instanceof CpsFlowFactoryAction2) {
-                return ((CpsFlowFactoryAction2) a).create(this, owner, actions)
+        WorkflowRun run = owner.run()
+        ReplayCause replay = run.getCause(ReplayCause)
+        RestartDeclarativePipelineCause restartDeclarative = run.getCause(RestartDeclarativePipelineCause)
+        if(replay || restartDeclarative){
+            WorkflowRun previous = replay ? replay.getOriginal() : restartDeclarative.getOriginal()
```
Comment (cokieffebah) [inline src/main/groovy/org/boozallen/plugins/jte/job/TemplateFlowDefinition.groovy:64]: does/should the Spec test both cases for ReplayCause and RestartDeclarativePipeline Cause?
deferring to your judgement

**Review by cokieffebah — APPROVED** [review]

File: src/main/groovy/org/boozallen/plugins/jte/job/TemplateFlowDefinition.groovy (hunk 1 above)
Comment (steven-terrana) [reply src/main/groovy/org/boozallen/plugins/jte/job/TemplateFlowDefinition.groovy:64]: it does in `DeclarativeSpec`... which is how i figured out i had to add that `RestartDeclarativePipelineCause` in addition to the ReplayCause.
