### PR TITLE
Expose JTE Primitives via GlobalVariables instead of the TemplateBinding

### LINKED ISSUE #188: External library declarative pipeline marshal errors
### Environment Information

- [x] Jenkins version 2.222.1
- [x] Plugin version 2.0.4
- [x] OS Debian 9

### Description

If I use an external library that contains a pipeline element from either the Jenkins file, or the provide default pipeline template from console box, I get an ugly exception about refusing to marshal.

Log:
```
[JTE] Obtained Template Configuration File
[JTE] -- scm: git https://XXXX
[JTE] -- file path: pipeline_config.groovy
[JTE] Pipeline Configuration Modifications
[JTE] Configurations Added:
[JTE] - application_environments set to [:]
[JTE] - libraries set to [:]
[JTE] Configurations Deleted: None
[JTE] Configurations Changed: None
[JTE] Configurations Duplicated: None
[JTE] Configurations Ignored: None
[JTE] Subsequent May Merge: None
[JTE] Subsequent May Override: None
[JTE] Obtained Repository Jenkinsfile
[JTE] -- scm: git https://XXXX
[JTE] -- file path: Jenkinsfile
Running in Durability level: MAX_SURVIVABILITY
Loading library jte-test-library
Attempting to resolve XXXX from remote references...
 > git --version # timeout=10
using GIT_SSH to set credentials XXXX
 > git ls-remote -h -- XXXX # timeout=10
Found match: XXXX revision XXXX
using credential XXXX
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url XXXX # timeout=10
Fetching without tags
Fetching upstream changes from XXXX
 > git --version # timeout=10
using GIT_SSH to set credentials XXXX
 > git fetch --no-tags --progress -- XXXX +refs/heads/*:refs/remotes/origin/* # timeout=10
Checking out Revision XXXX
 > git config core.sparsecheckout # timeout=10
 > git checkout -f XXXX # timeout=10
Commit message: XXXX
 > git rev-list --no-walk XXXX # timeout=10
Excluding src/test/ from checkout of git XXXX so that shared library test code cannot be accessed by Pipelines.
To remove this log message, move the test code outside of src/. To restore the previous behavior that allowed access to files in src/test/, pass -Dorg.jenkinsci.plugins.workflow.libs.SCMSourceRetriever.INCLUDE_SRC_TEST_IN_LIBRARIES=true to the java command used to start Jenkins.
[Pipeline] Start of Pipeline
[Pipeline] End of Pipeline
java.lang.UnsupportedOperationException: Refusing to marshal groovy.lang.Binding for security reasons; see https://jenkins.io/redirect/class-filter/
	at hudson.util.XStream2$BlacklistedTypesConverter.marshal(XStream2.java:541)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:250)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:226)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.<init>(AbstractReflectionConverter.java:189)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:135)
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter.marshalUnserializableParent(SerializableConverter.java:292)
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter.doMarshal(SerializableConverter.java:246)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:83)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
	at com.thoughtworks.xstream.converters.collections.MapConverter.marshal(MapConverter.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:262)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:249)
Caused: java.lang.RuntimeException: Failed to serialize groovy.lang.Binding#variables for class org.boozallen.plugins.jte.init.primitives.TemplateBinding
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:253)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:221)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:207)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:148)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:262)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:249)
Caused: java.lang.RuntimeException: Failed to serialize org.boozallen.plugins.jte.init.PipelineDecorator#binding for class org.boozallen.plugins.jte.init.PipelineDecorator
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:253)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:221)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:207)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:148)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:88)
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.writeItem(AbstractCollectionConverter.java:64)
	at com.thoughtworks.xstream.converters.collections.CollectionConverter.marshal(CollectionConverter.java:74)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:84)
	at hudson.util.RobustReflectionConverter.marshallField(RobustReflectionConverter.java:262)
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:249)
Caused: java.lang.RuntimeException: Failed to serialize hudson.model.Actionable#actions for class org.jenkinsci.plugins.workflow.job.WorkflowRun
	at hudson.util.RobustReflectionConverter$2.writeField(RobustReflectionConverter.java:253)
	at hudson.util.RobustReflectionConverter$2.visit(RobustReflectionConverter.java:221)
	at com.thoughtworks.xstream.converters.reflection.PureJavaReflectionProvider.visitSerializableFields(PureJavaReflectionProvider.java:138)
	at hudson.util.RobustReflectionConverter.doMarshal(RobustReflectionConverter.java:207)
	at hudson.util.RobustReflectionConverter.marshal(RobustReflectionConverter.java:148)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:69)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:58)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:43)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:82)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1026)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1015)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:988)
	at hudson.XmlFile.write(XmlFile.java:195)
	at org.jenkinsci.plugins.workflow.support.PipelineIOUtils.writeByXStream(PipelineIOUtils.java:30)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.save(WorkflowRun.java:1210)
	at sun.reflect.GeneratedMethodAccessor1135.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at org.jenkinsci.plugins.pipeline.modeldefinition.Utils.updateRunAndJobActions(Utils.groovy:302)
	at org.jenkinsci.plugins.pipeline.modeldefinition.Utils$updateRunAndJobActions$4.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
Caused: java.io.IOException
	at hudson.XmlFile.write(XmlFile.java:202)
	at org.jenkinsci.plugins.workflow.support.PipelineIOUtils.writeByXStream(PipelineIOUtils.java:30)
	at org.jenkinsci.plugins.workflow.job.WorkflowRun.save(WorkflowRun.java:1210)
	at sun.reflect.GeneratedMethodAccessor1135.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
	at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at org.jenkinsci.plugins.pipeline.modeldefinition.Utils.updateRunAndJobActions(Utils.groovy:302)
	at org.jenkinsci.plugins.pipeline.modeldefinition.Utils$updateRunAndJobActions$4.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at com.cloudbees.groovy.cps.sandbox.DefaultInvoker.methodCall(DefaultInvoker.java:20)
	at org.jenkinsci.plugins.pipeline.modeldefinition.ModelInterpreter.call(ModelInterpreter.groovy:66)
	at traditionalPipeline.call(traditionalPipeline.groovy:2)
	at WorkflowScript.run(WorkflowScript:2)
	at ___cps.transform___(Native Method)
	at com.cloudbees.groovy.cps.impl.ContinuationGroup.methodCall(ContinuationGroup.java:86)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.dispatchOrArg(FunctionCallBlock.java:113)
	at com.cloudbees.groovy.cps.impl.FunctionCallBlock$ContinuationImpl.fixArg(FunctionCallBlock.java:83)
	at sun.reflect.GeneratedMethodAccessor450.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.get(PropertyishBlock.java:76)
	at com.cloudbees.groovy.cps.LValueBlock$GetAdapter.receive(LValueBlock.java:30)
	at com.cloudbees.groovy.cps.impl.PropertyishBlock$ContinuationImpl.fixName(PropertyishBlock.java:66)
	at sun.reflect.GeneratedMethodAccessor642.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.cloudbees.groovy.cps.impl.ContinuationPtr$ContinuationImpl.receive(ContinuationPtr.java:72)
	at com.cloudbees.groovy.cps.impl.ConstantBlock.eval(ConstantBlock.java:21)
	at com.cloudbees.groovy.cps.Next.step(Next.java:83)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:174)
	at com.cloudbees.groovy.cps.Continuable$1.call(Continuable.java:163)
	at org.codehaus.groovy.runtime.GroovyCategorySupport$ThreadCategoryInfo.use(GroovyCategorySupport.java:129)
	at org.codehaus.groovy.runtime.GroovyCategorySupport.use(GroovyCategorySupport.java:268)
	at com.cloudbees.groovy.cps.Continuable.run0(Continuable.java:163)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.access$001(SandboxContinuable.java:18)
	at org.jenkinsci.plugins.workflow.cps.SandboxContinuable.run0(SandboxContinuable.java:51)
	at org.jenkinsci.plugins.workflow.cps.CpsThread.runNextChunk(CpsThread.java:185)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.run(CpsThreadGroup.java:400)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup.access$400(CpsThreadGroup.java:96)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:312)
	at org.jenkinsci.plugins.workflow.cps.CpsThreadGroup$2.call(CpsThreadGroup.java:276)
	at org.jenkinsci.plugins.workflow.cps.CpsVmExecutorService$2.call(CpsVmExecutorService.java:67)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:131)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Finished: FAILURE
```

Jenkinsfile:
```
@Library('jte-test-library') _
testLibrary()
````
testLibrary.groovy:
```
def call() {
    pipeline {
        agent none
        stages {
            stage('whee') {
                steps {
                    script {
                        echo "why"
                    }
                }
            }
        }
    }
}
````
pipeline_config.groovy:
```
application_environments {
}

libraries {
}
```

To isolate it as much as possible, I currently have nothing set globally for JTE, just at the multibranch pipeline job level.

Adding -Dhudson.remoting.ClassFilter=groovy.lang.Binding gets past this initial error as others have suggested on gitter, but that's kind of ugly.
I'm still trying to figure out some other things that broke in our code between 1.5 and 2.0.4.

### PR DESCRIPTION
**Pull request by steven-terrana**
# PR Details

This PR hopefully fixes #188  and all cases of

> java.lang.UnsupportedOperationException: Refusing to marshal * for security reasons;

## Description

Until now, all JTE Pipeline Primitives like steps, stages, keywords, application_environments were instantiated as objects and stored in a common `TemplateBinding`. 

This TemplateBinding was needed several times in different contexts and was therefore stored as an `InvisibleAction`. 

Objects serialized via `Actions` are subject to [JEP-200](https://github.com/jenkinsci/jep/blob/master/jep/200/README.adoc) which meant that we needed to maintain a custom `ClassFilterImpl`. 

This quickly grew unmanageable as it meant that any user defined variable in the binding would need to be added to the `ClassFilterImpl`. 

This PR resolves the issue by demoting the role of `TemplateBinding` to that of a runtime collision detector and instead surfaces `TemplatePrimitives` via a `GlobalVariableSet`. 

Overall, this was a pretty substantial PR:
>  50 files changed, 1526 insertions(+), 2496 deletions(-)

Fortunately, the change actually simplified JTE internals a bit. 

## How Has This Been Tested

Used myself for a week or so. Unit tests continuing to pass. 

## Types of Changes

- [x] Docs change / refactoring / dependency upgrade
- [x] Added Unit Testing
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have added the appropriate label for this PR
- [x] If necessary, I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitiveInjector.groovy [hunk 1]
```diff
@@ -93,22 +97,117 @@ abstract class TemplatePrimitiveInjector implements ExtensionPoint{
...
+    void validatePrimitives(FlowExecutionOwner flowOwner, PipelineConfigurationObject config){}
+
+    TemplatePrimitiveCollector getPrimitiveCollector(FlowExecutionOwner flowOwner){
+        WorkflowRun run = flowOwner.run()
+        if(!run){
+            throw new JTEException("Invalid Context. Cannot determine run.")
+        }
+        TemplatePrimitiveCollector primitiveCollector = run.getAction(TemplatePrimitiveCollector)
+        if(primitiveCollector == null){
+            primitiveCollector = new TemplatePrimitiveCollector()
```
Comment (cokieffebah) [inline src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitiveInjector.groovy:124]: Dont fully understand the action part so, asking, if `run.getAction(TemplatePrimitiveCollector)` is null, do we want to insert this instance as run.getAction(TemplatePrimitiveCollector) or should each call to getPrimitiveCollecter return a new instance

File: src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitive.groovy [hunk 2]
```diff
@@ -16,57 +16,63 @@
...
-     * Returns the injector that creates the primitive
-     * <p>
-     * implementing classes must mark this method @NonCPS lest a CpsCallableInvocation be thrown
-     * during initialization
-     * @return
-     */
-    abstract Class<? extends TemplatePrimitiveInjector> getInjector()
+    @Override
+    @NonCPS
+    Object getValue(@Nonnull CpsScript script) throws Exception {
```
Comment (cokieffebah) [inline src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitive.groovy:46]: maybe refactor the overload check and exception into another method that is reused by subclasses

File: src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitive.groovy [hunk 3]
```diff
@@ -16,57 +16,63 @@
...
 /**
- * Objects whose class extends TemplatePrimitive will be protected in the {@link TemplateBinding} from
- * being inadvertently overridden
+ * Framework constructs that make templates easier to write.
+ * Typically created by parsing the Pipeline Configuration.
  */
-abstract class TemplatePrimitive implements Serializable{
+abstract class TemplatePrimitive extends GlobalVariable implements Serializable{
 
     private static final long serialVersionUID = 1L
```
[the remark this answers is not in the document]
Comment (steven-terrana) [reply src/main/groovy/org/boozallen/plugins/jte/init/primitives/TemplatePrimitive.groovy:32]: The `TemplatePrimitive` only gets persisted to a job as part of the binding.  This wouldn't be unmarshalled because if someone were to replay the job we'd create a new binding anyway.

**Review by cokieffebah — APPROVED** [review]
