### PR TITLE
Resolve exceptions when loading more than 128 files

### LINKED ISSUE #256: [Bug]: The JTE pipeline job cannot load more than 128 files
### Jenkins Version

2.277.3

### JTE Version

2.3

### Bug Description

the JTE pipeline uses :
Pipeline_configuration and Libraries 
When I used 129 files in my jte pipeline including steps in all read Libraries and pipeline_configuration files [pipeline_config.groovy and pipeline_template files] 
Issue appeared with below error :
[JTE] Cannot cast object '[]' with class 'java.util.LinkedHashSet' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List() 

### Relevant log output

```shell
[JTE] Cannot cast object '[]' with class 'java.util.LinkedHashSet' to class 'java.util.List' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: java.util.List()
```

### Steps to Reproduce

try to use more than 128 files to be loaded in your pipeline

### PR DESCRIPTION
**Pull request by steven-terrana**
# PR Details

The `GlobalCollisionValidator` would previously throw an exception when more than 128 steps were loaded.
Explicitly casting to a `List` resolves this error. 

fixes #256 

## How Has This Been Tested

Behavior reproduced both via a test and manually in a live Jenkins instance.
The test now passes and the fix has been confirmed against a live Jenkins instance.

## Types of Changes

- [x] Added Unit Testing
- [ ] Docs change / refactoring / dependency upgrade
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] I have added the appropriate label for this PR
- [x] If necessary, I have updated the documentation accordingly.
- [x] All new and existing tests passed.

### CODE REVIEW

File: src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/GlobalCollisionValidator.groovy [hunk 1]
```diff
@@ -95,7 +95,7 @@ import org.jenkinsci.plugins.workflow.steps.StepDescriptor
         List<String> functionNames = StepDescriptor.all().collect { step ->
             step.getFunctionName()
         }
-        List<String> stepCollisions = primitivesByName.keySet().intersect(functionNames)
+        List<String> stepCollisions = primitivesByName.keySet().intersect(functionNames) as List
```
Comment (cokieffebah) [inline src/main/groovy/org/boozallen/plugins/jte/init/primitives/injectors/GlobalCollisionValidator.groovy:98]: I think the real issue here is that keySet().intersect( ... ) is expecting a set so it bombs when there is a non-empty `functionNames` : https://github.com/jenkinsci/templating-engine-plugin/issues/250
